/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    colors: {
      'secondary': '#4e5e81',
      'primary-fixed': '#d8e2ff',
      'tertiary-container': '#944000',
      'secondary-fixed-dim': '#b6c6ef',
      'inverse-surface': '#2d3133',
      'surface-tint': '#235cb3',
      'tertiary': '#6f2e00',
      'on-secondary': '#ffffff',
      'surface': '#f8f9fb',
      'secondary-container': '#c3d4fd',
      'surface-container-low': '#f2f4f6',
      'on-error': '#ffffff',
      'on-primary-fixed': '#001a41',
      'error': '#ba1a1a',
      'surface-container-lowest': '#ffffff',
      'tertiary-fixed': '#ffdbca',
      'on-surface-variant': '#424752',
      'primary-fixed-dim': '#adc6ff',
      'inverse-on-surface': '#eff1f3',
      'outline': '#737783',
      'surface-container': '#eceef0',
      'surface-variant': '#e0e3e5',
      'on-background': '#191c1e',
      'background': '#f8f9fb',
      'primary': '#003f89',
      'on-tertiary-fixed': '#331100',
      'outline-variant': '#c3c6d4',
      'on-error-container': '#93000a',
      'secondary-fixed': '#d8e2ff',
      'on-secondary-fixed-variant': '#364768',
      'on-primary-container': '#bbd0ff',
      'primary-container': '#1a56ad',
      'on-tertiary-container': '#ffc3a4',
      'on-tertiary': '#ffffff',
      'inverse-primary': '#adc6ff',
      'surface-container-high': '#e6e8ea',
      'error-container': '#ffdad6',
      'on-primary': '#ffffff',
      'on-primary-fixed-variant': '#004494',
      'tertiary-fixed-dim': '#ffb68f',
      'on-surface': '#191c1e',
      'on-secondary-container': '#4b5b7e',
      'surface-container-highest': '#e0e3e5',
      'surface-dim': '#d8dadc',
      'on-tertiary-fixed-variant': '#773200',
      'surface-bright': '#f8f9fb',
      'on-secondary-fixed': '#071b3a',
      },
    extend: {
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Public Sans'],
        body: ['Public Sans'],
        label: ['Public Sans'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
